### ISSUE TITLE
where da filez at?

### ISSUE THREAD

**Issue by adamgall** [hjhart/ynab-amazon-importer#1]
Did you forget to `git add` your script? All I see in the repo is the license, readme, and an image.

**Comment by hjhart** [comment]
TODO: Write any code at all.

Haha, no, sorry, I started development with the README.md. Gauging how much interest there right now on [/r/YNAB](https://www.reddit.com/r/ynab/comments/5flk6w/concept_import_your_amazon_transactions_into_ynab/) currently, but I'll probably start working on it sometime soon.

**Comment by adamgall** [comment]
Oooh, ok my bad. That's probably why the reddit post is titled "Concept: ..." 😅

**Comment by hjhart** [comment]
No problem at all. 😄
