### ISSUE TITLE
`memo': undefined method `>'

### ISSUE THREAD

**Issue by russellgeoff** [hjhart/ynab-amazon-importer#2]
Hi,

I get the following error when I try to use the program as described in the documentation:

/ynab-amazon-importer/app/models/item.rb:10:in `memo': undefined method `>' for nil:NilClass (NoMethodError)

Here is the command I ran:
./bin/ynab_transactions ./01-Dec-2017_to_25-Feb-2018_Order.csv ./01-Dec-2017_to_25-Feb-2018_Items.csv

Thank you!

**Comment by hjhart** [comment]
Without the data it will be pretty hard to figure out what is going on.

Can you include those two files in the issue?

**Comment by russellgeoff** [comment]
So I think I found my issue... I swapped the arguments to the function. I put orders.csv then items.csv when it should have been items.csv then orders.csv. Here's the command that worked for me:
`./bin/ynab_transactions ./01-Dec-2017_to_25-Feb-2018_Items.csv ./01-Dec-2017_to_25-Feb-2018_Order.csv `

Thanks for making this! Works like a charm and makes managing Amazon changes in YNAB way better!

**Comment by jeff47** [comment]
Wait... so items comes first and "order and shipments" comes second, opposite to the docs?  That's very confusing!

**Comment by hjhart** [comment]
> Wait... so items comes first and "order and shipments" comes second, opposite to the docs?  That's very confusing!

I'm not using this script anymore. - so I can't speak to that. I should archive the repository. If you want to submit an update to the docs, I'll gladly merge that in.

**Comment by jeff47** [comment]
Ah, OK.  Did you switch to an alternative method, or just find it wasn't work the effort to categorize Amazon transactions?

**Comment by hjhart** [comment]
I stopped using YNAB altogether. 

via mobile
