### ISSUE TITLE
Reports Endpoint is gone

### ISSUE THREAD

**Issue by octosteve** [hjhart/ynab-amazon-importer#3]
Clicking the link to the b2b report redirects to your order history. As of right now, there's no way to export an itemized report. At least I don't think there is.

**Comment by hjhart** [comment]
Damn. I stopped using this a long time ago anyhow. I should be better about adding a deprecated warning in repos.

**Comment by hjhart** [comment]
Huh, I was able to go directly to that url (https://www.amazon.com/gp/b2b/reports) and it didn't redirect. The top of the page says "Order History", but the screen looks identical to the screenshot in the README.

**Comment by octosteve** [comment]
I swear this didn't work when I opened the issue :-). It's up now.
